# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/ArthurHlt/go-eureka-client"

[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/ty"

[[constraint]]
  branch = "master"
  name = "github.com/NYTimes/gziphandler"

[[constraint]]
  branch = "containous-fork"
  name = "github.com/abbot/go-http-auth"
  source = "github.com/containous/go-http-auth"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.11"

[[constraint]]
  branch = "master"
  name = "github.com/cenk/backoff"

[[constraint]]
  name = "github.com/containous/flaeg"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/containous/mux"

[[constraint]]
  name = "github.com/containous/staert"
  version = "3.1.1"

[[constraint]]
  name = "github.com/containous/traefik-extra-service-fabric"
  version = "1.3.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "14.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/leadership"
  source = "github.com/containous/leadership"

[[constraint]]
  name = "github.com/eapache/channels"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  branch = "fork-containous"
  name = "github.com/go-check/check"
  source = "github.com/containous/check"

[[override]]
  branch = "fork-containous"
  name = "github.com/go-check/check"
  source = "github.com/containous/check"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.6"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.3.7"

[[constraint]]
  branch = "master"
  name = "github.com/jjcollinge/servicefabric"

[[constraint]]
  branch = "master"
  name = "github.com/abronan/valkeyrie"

[[constraint]]
  name = "github.com/mesosphere/mesos-dns"
  source = "https://github.com/containous/mesos-dns.git"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  branch = "containous-fork"
  name = "github.com/rancher/go-rancher-metadata"
  source = "github.com/containous/go-rancher-metadata"

[[constraint]]
  branch = "master"
  name = "github.com/ryanuber/go-glob"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/stvp/go-udp-testing"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.10.0"

[[constraint]]
  name = "github.com/uber/jaeger-lib"
  version = "1.1.0"

[[constraint]]
  branch = "v1"
  name = "github.com/unrolled/secure"

[[constraint]]
  name = "github.com/vdemeester/shakers"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/vulcand/oxy"

[[constraint]]
#  branch = "master"
  name = "github.com/xenolf/lego"
  version = "2.0.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.2"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/libkermit/docker"

[[constraint]]
  branch = "master"
  name = "github.com/libkermit/docker-check"

[[constraint]]
  branch = "master"
  name = "github.com/libkermit/compose"

[[constraint]]
 name = "github.com/docker/docker"
 revision = "7848b8beb9d38a98a78b75f78e05f8d2255f9dfe"

[[override]]
 name = "github.com/docker/docker"
 revision = "7848b8beb9d38a98a78b75f78e05f8d2255f9dfe"

[[override]]
 name = "github.com/docker/cli"
 revision = "6b63d7b96a41055baddc3fa71f381c7f60bd5d8e"

[[override]]
 name = "github.com/docker/distribution"
 revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  branch = "master"
  name = "github.com/docker/libcompose"

[[override]]
  name = "github.com/Nvveen/Gotty"
  revision = "a8b993ba6abdb0e0c12b0125c603323a71c7790c"
  source = "github.com/ijc25/Gotty"

[[override]]
  # ALWAYS keep this override
  name = "github.com/mailgun/timetools"
  revision = "7e6055773c5137efbeb3bd2410d705fe10ab6bfd"

[[override]]
  version = "v1.1.1"
  name = "github.com/miekg/dns"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "gopkg.in/DataDog/dd-trace-go.v1"
  version = "1.7.0"
