# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/sirupsen/logrus"]

[[constraint]]
  branch = "master"
  name = "github.com/ArthurHlt/go-eureka-client"

[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/ty"

[[constraint]]
  branch = "master"
  name = "github.com/NYTimes/gziphandler"

[[constraint]]
  branch = "containous-fork"
  name = "github.com/abbot/go-http-auth"
  source = "github.com/containous/go-http-auth"

[[constraint]]
  branch = "master"
  name = "github.com/armon/go-proxyproto"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.6.18"

[[constraint]]
  branch = "master"
  name = "github.com/cenk/backoff"

[[constraint]]
  name = "github.com/containous/flaeg"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/containous/mux"

[[constraint]]
  name = "github.com/containous/staert"
  version = "2.1.0"

[[constraint]]
  name = "github.com/containous/traefik-extra-service-fabric"
  version = "1.0.5"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "14.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/leadership"
  source = "github.com/containous/leadership"

[[constraint]]
  name = "github.com/docker/libkv"
  source = "github.com/abronan/libkv"

[[constraint]]
  name = "github.com/eapache/channels"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  name = "github.com/go-check/check"
  source = "github.com/containous/check"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.3.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.3.7"

[[constraint]]
  branch = "master"
  name = "github.com/jjcollinge/servicefabric"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  name = "github.com/mesosphere/mesos-dns"
  source = "https://github.com/containous/mesos-dns.git"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/rancher/go-rancher-metadata"

[[constraint]]
  branch = "master"
  name = "github.com/ryanuber/go-glob"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/stvp/go-udp-testing"

[[constraint]]
  name = "github.com/vdemeester/shakers"
  version = "0.1.0"

[[constraint]]
  branch = "containous-fork"
  name = "github.com/vulcand/oxy"
  source = "https://github.com/containous/oxy.git"

[[constraint]]
  name = "github.com/xenolf/lego"
  version = "0.4.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.2"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "2.0.0"

[[override]]
  name = "github.com/Nvveen/Gotty"
  revision = "6018b68f96b839edfbe3fb48668853f5dbad88a3"
  source = "github.com/ijc25/Gotty"

[[override]]
  # always keep this override
  name = "github.com/mailgun/timetools"
  revision = "7e6055773c5137efbeb3bd2410d705fe10ab6bfd"

[[override]]
  name = "github.com/vulcand/predicate"
  revision = "19b9dde14240d94c804ae5736ad0e1de10bf8fe6"

[[override]]
  # remove override on master
  name = "github.com/coreos/bbolt"
  revision = "32c383e75ce054674c53b5a07e55de85332aee14"

[[override]]
  branch = "master"
  name = "github.com/miekg/dns"

[[override]]
  name = "golang.org/x/crypto"
  revision = "b080dc9a8c480b08e698fb1219160d598526310f"

[[override]]
  name = "golang.org/x/net"
  revision = "894f8ed5849b15b810ae41e9590a0d05395bba27"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
