site_name: Træfik
site_description: Træfik Documentation
site_author: containo.us
site_url: https://docs.traefik.io

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/traefik'

# Documentation and theme
docs_dir: 'docs'
theme: united
# theme: readthedocs
# theme: 'material'
# theme: bootstrap

site_favicon: 'img/traefik.icon.png'

# Copyright
copyright: "Copyright &copy; 2016-2017 Containous SAS"

# Options
extra:
#   version: 0.2.2
  logo: img/traefik.logo.png
  # author:
  #   twitter: traefikproxy
  palette:
    primary: 'blue'
    accent: 'light blue'
  i18n:
    prev: 'Previous'
    next: 'Next'  
  
markdown_extensions:
#   - codehilite(css_class=code)
  - admonition
#   - toc:
#       permalink: '##'
  # - fenced_code
      
extra_css:
    - css/traefik.css
      
# Page tree
pages:
  - Getting Started: index.md
  - Basics: basics.md
  - traefik.toml: toml.md
  - User Guide:
      - 'Configuration examples': 'user-guide/examples.md'
      - 'Swarm cluster': 'user-guide/swarm.md'
      - 'Swarm mode cluster': 'user-guide/swarm-mode.md'
      - 'Kubernetes': 'user-guide/kubernetes.md'
      - 'Key-value store configuration': 'user-guide/kv-config.md'
      - 'Clustering/HA': 'user-guide/cluster.md'
  - Benchmarks: benchmarks.md
