site_name: Traefik
site_description: Traefik Documentation
site_author: containo.us
site_url: https://docs.traefik.io
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/traefik'
edit_uri: 'edit/v1.7/docs/'

docs_dir: 'docs'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: en
  include_sidebar: true
  favicon: img/traefik.icon.png
  logo: img/traefik.logo.png
  palette:
    primary: 'cyan'
    accent: 'cyan'
  feature:
    tabs: false
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2016-2019 Containous"

google_analytics:
  - 'UA-51880359-3'
  - 'docs.traefik.io'

# Options
# Comment because the call of the CDN is very slow.
#extra:
#  social:
#    - type: 'github'
#      link: 'https://github.com/containous/traefik'
#    - type: 'stack-overflow'
#      link: 'https://stackoverflow.com/questions/tagged/traefik'
#    - type: 'slack'
#      link: 'https://slack.traefik.io'
#    - type: 'twitter'
#      link: 'https://twitter.com/traefik'

extra_css:
  - theme/styles/extra.css
  - theme/styles/atom-one-light.css

extra_javascript:
  - theme/js/hljs/highlight.pack.js
  - theme/js/extra.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true

# Page tree
pages:
  - Getting Started: index.md
  - Basics: basics.md
  - Configuration:
    - 'Commons': 'configuration/commons.md'
    - 'Logs': 'configuration/logs.md'
    - 'EntryPoints': 'configuration/entrypoints.md'
    - 'Let''s Encrypt': 'configuration/acme.md'
    - 'API / Dashboard': 'configuration/api.md'
    - 'BoltDB': 'configuration/backends/boltdb.md'
    - 'Consul': 'configuration/backends/consul.md'
    - 'Consul Catalog': 'configuration/backends/consulcatalog.md'
    - 'Docker': 'configuration/backends/docker.md'
    - 'DynamoDB': 'configuration/backends/dynamodb.md'
    - 'ECS': 'configuration/backends/ecs.md'
    - 'Etcd': 'configuration/backends/etcd.md'
    - 'Eureka': 'configuration/backends/eureka.md'
    - 'File': 'configuration/backends/file.md'
    - 'Kubernetes Ingress': 'configuration/backends/kubernetes.md'
    - 'Marathon': 'configuration/backends/marathon.md'
    - 'Mesos': 'configuration/backends/mesos.md'
    - 'Rancher': 'configuration/backends/rancher.md'
    - 'Rest': 'configuration/backends/rest.md'
    - 'Azure Service Fabric': 'configuration/backends/servicefabric.md'
    - 'Zookeeper': 'configuration/backends/zookeeper.md'
    - 'Ping': 'configuration/ping.md'
    - 'Metrics': 'configuration/metrics.md'
    - 'Tracing': 'configuration/tracing.md'
    - 'Web (Deprecated)': 'configuration/backends/web.md'
  - User Guides:
    - 'Configuration Examples': 'user-guide/examples.md'
    - 'Swarm Mode Cluster': 'user-guide/swarm-mode.md'
    - 'Swarm Cluster': 'user-guide/swarm.md'
    - 'Let''s Encrypt & Docker': 'user-guide/docker-and-lets-encrypt.md'
    - 'Kubernetes': 'user-guide/kubernetes.md'
    - 'Marathon': 'user-guide/marathon.md'
    - 'Key-value Store Configuration': 'user-guide/kv-config.md'
    - 'Clustering/HA': 'user-guide/cluster.md'
    - 'gRPC Example': 'user-guide/grpc.md'
    - 'Traefik cluster example with Swarm': 'user-guide/cluster-docker-consul.md'
