site_name: Træfik
site_description: Træfik Documentation
site_author: containo.us
site_url: https://docs.traefik.io

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/traefik'

# Documentation
docs_dir: 'docs'

#theme: united
#theme: readthedocs
theme: 'material'
#theme: bootstrap

site_favicon: 'img/traefik.icon.png'

copyright: "Copyright &copy; 2016-2017 Containous SAS"

google_analytics:
  - 'UA-51880359-3'
  - 'docs.traefik.io'

# Options
extra:
  logo: img/traefik.logo.png
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'
# Comment because the call of the CDN is very slow.
#  social:
#    - type: 'github'
#      link: 'https://github.com/containous/traefik'
#    - type: 'stack-overflow'
#      link: 'https://stackoverflow.com/questions/tagged/traefik'
#    - type: 'slack'
#      link: 'https://traefik.herokuapp.com'
#    - type: 'twitter'
#      link: 'https://twitter.com/traefikproxy'

theme_dir: docs/theme/

extra_css:
  - theme/styles/extra.css
  - theme/styles/atom-one-light.css

extra_javascript:
  - theme/js/hljs/highlight.pack.js
  - theme/js/extra.js

markdown_extensions:
  - admonition
#  - codehilite(guess_lang=false)
  - toc(permalink=true)

# Page tree
pages:
  - Getting Started: index.md
  - Basics: basics.md
  - Configuration:
    - 'Commons': 'configuration/commons.md'
    - 'EntryPoints': 'configuration/entrypoints.md'
    - 'Let''s Encrypt': 'configuration/acme.md'
    - 'Backend: Web': 'configuration/backends/web.md'
    - 'Backend: BoltDB': 'configuration/backends/boltdb.md'
    - 'Backend: Consul': 'configuration/backends/consul.md'
    - 'Backend: Docker': 'configuration/backends/docker.md'
    - 'Backend: DynamoDB': 'configuration/backends/dynamodb.md'
    - 'Backend: ECS': 'configuration/backends/ecs.md'
    - 'Backend: Etcd': 'configuration/backends/etcd.md'
    - 'Backend: Eureka': 'configuration/backends/eureka.md'
    - 'Backend: File': 'configuration/backends/file.md'
    - 'Backend: Kubernetes Ingress': 'configuration/backends/kubernetes.md'
    - 'Backend: Marathon': 'configuration/backends/marathon.md'
    - 'Backend: Mesos': 'configuration/backends/mesos.md'
    - 'Backend: Rancher': 'configuration/backends/rancher.md'
    - 'Backend: Zookeeper': 'configuration/backends/zookeeper.md'
  - User Guides:
    - 'Configuration Examples': 'user-guide/examples.md'
    - 'Swarm Mode Cluster': 'user-guide/swarm-mode.md'
    - 'Swarm Cluster': 'user-guide/swarm.md'
    - 'Let''s Encrypt & Docker': 'user-guide/docker-and-lets-encrypt.md'
    - 'Kubernetes': 'user-guide/kubernetes.md'
    - 'Marathon': 'user-guide/marathon.md'
    - 'Key-value Store Configuration': 'user-guide/kv-config.md'
    - 'Clustering/HA': 'user-guide/cluster.md'
    - 'gRPC Example': 'user-guide/grpc.md'
  - Benchmarks: benchmarks.md
