blank_issues_enabled: false
contact_links:
  - name: Baqup Community Support
    url: https://community.baqup.io/
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!
  - name: Baqup Helm Chart Issues
    url: https://github.com/baqupio/baqup-helm-chart
    about: Are you submitting an issue or feature enhancement for the Baqup helm chart? Please post in the baqup-helm-chart GitHub Issues.
