Owner = "baqup"
RepositoryName = "baqup"

OutputType = "file"
FileName = "baqup_changelog.md"

# example final release of v3.6.0
CurrentRef = "v3.6"
PreviousRef = "v3.6.0-rc1"
BaseBranch = "v3.6"
FutureCurrentRefName = "v3.6.0"

ThresholdPreviousRef = 10
ThresholdCurrentRef = 10

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
