Owner = "traefik"
RepositoryName = "traefik"

OutputType = "file"
FileName = "traefik_changelog.md"

# example RC6 of v2.5.0
CurrentRef = "v2.5"
PreviousRef = "v2.5.0-rc5"
BaseBranch = "v2.5"
FutureCurrentRefName = "v2.5.0-rc6"

ThresholdPreviousRef = 10
ThresholdCurrentRef = 10

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
