Owner = "traefik"
RepositoryName = "traefik"

OutputType = "file"
FileName = "traefik_changelog.md"

# example new bugfix v2.11.34
CurrentRef = "v2.11"
PreviousRef = "v2.11.33"
BaseBranch = "v2.11"
FutureCurrentRefName = "v2.11.34"

ThresholdPreviousRef = 10000
ThresholdCurrentRef = 10000

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
