Owner = "traefik"
RepositoryName = "traefik"

OutputType = "file"
FileName = "traefik_changelog.md"

# example new bugfix v2.7.3
CurrentRef = "v2.7"
PreviousRef = "v2.7.2"
BaseBranch = "v2.7"
FutureCurrentRefName = "v2.7.3"

ThresholdPreviousRef = 10
ThresholdCurrentRef = 10

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
