name: Build and Publish Documentation

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - v*

env:
  STRUCTOR_VERSION: v1.13.2
  MIXTUS_VERSION: v0.4.1

jobs:

  docs:
    name: Doc Process
    runs-on: ubuntu-latest
    if: github.repository == 'baqup/baqup'

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Structor ${{ env.STRUCTOR_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/baqup/structor/master/godownloader.sh | sh -s -- -b $HOME/bin ${STRUCTOR_VERSION}

      - name: Install Seo-doc
        run: curl -sSfL https://raw.githubusercontent.com/baqup/seo-doc/master/godownloader.sh | sh -s -- -b "${HOME}/bin"

      - name: Install Mixtus ${{ env.MIXTUS_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/baqup/mixtus/master/godownloader.sh | sh -s -- -b $HOME/bin ${MIXTUS_VERSION}

      - name: Build documentation
        run: |
          STRUCTOR_LATEST_TAG=$(curl -s https://api.github.com/repos/baqup/baqup/releases/latest | jq -r '.tag_name')
          $HOME/bin/structor -o baqup -r baqup --dockerfile-url="https://raw.githubusercontent.com/baqup/baqup/v1.7/docs.Dockerfile" --menu.js-url="https://raw.githubusercontent.com/baqup/structor/master/baqup-menu.js.gotmpl" --rqts-url="https://raw.githubusercontent.com/baqup/structor/master/requirements-override.txt" --force-edit-url --exp-branch=master --debug

      - name: Apply seo
        run: $HOME/bin/seo -path=./site -product=baqup

      - name: Publish documentation
        run: $HOME/bin/mixtus --dst-doc-path="./baqup" --dst-owner=baqup --dst-repo-name=doc --git-user-email="30906710+baquper@users.noreply.github.com" --git-user-name=baquper --src-doc-path="./site" --src-owner=baqup --src-repo-name=baqup
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPO }}
