name: Test Knative conformance

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/test-knative-conformance.yaml'
      - 'pkg/provider/kubernetes/knative/**'
      - 'integration/fixtures/knative/**'
      - 'integration/knative_conformance_test.go'
      - 'integration/integration_test.go'

env:
  GO_VERSION: '1.24'
  CGO_ENABLED: 0

jobs:

  test-knative-conformance:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up KO
        uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        env:
          KO_DOCKER_REPO: ko.local

      - name: Upload Test Images
        run: |
          # Download the test image templates.
          go mod vendor
          ./integration/fixtures/knative/upload-test-images.sh

      - name: Avoid generating webui
        run: |
          touch webui/static/index.html

      - name: Knative conformance test
        run: |
          make test-knative-conformance
