name: Test K8s Gateway API conformance

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/test-gateway-api-conformance.yaml'
      - 'pkg/provider/kubernetes/gateway/**'
      - 'integration/fixtures/gateway-api-conformance/**'
      - 'integration/gateway_api_conformance_test.go'
      - 'integration/integration_test.go'

env:
  GO_VERSION: '1.24'
  CGO_ENABLED: 0

jobs:

  test-gateway-api-conformance:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Avoid generating webui
        run: |
          touch webui/static/index.html

      - name: Gateway API conformance test and report
        run: |
          make test-gateway-api-conformance
          git diff --exit-code
